model_args:
  skeleton_feature_dim: 3
  conv3D_out_dim: 256
  graph: graph.kinetics.AdjMatrixGraph
  num_scales: 8
  window_size: 16
  window_stride: 16
  window_dilation: 1
  vertices_fusion_out_dim: 2048
  CPGB_hidden_channels: [512,128,64]
  num_class: 1
  kappa: 8
  CPGB_dropout: 0.5
  CPGB_activation: relu
  LSTM_hidden_channel: 1024
  OAMB_linear_hidden_channels: [512,128,64]
  OAMB_dropout: 0.5